name: Deploy to Cloud Function
on:
  push:
    branches:
      - main

env:
  GOOGLE_CLOUD_PROJECT: gain-data

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel setuptools

      - name: Install dependencies
        env:
          GEMFURY_TOKEN: ${{ secrets.GEMFURY_TOKEN }}
        run: pipenv install --deploy --dev

      - name: Generate requirements.txt
        env:
          GEMFURY_TOKEN: ${{ secrets.GEMFURY_TOKEN }}
        run: |
          pipenv requirements > requirements.txt

      - name: Clear out pipenv materials
        run: rm Pipfile Pipfile.lock
